### ISSUE TITLE
NodeMCU v1.0 ESP8266 LiPoly/LiIon Backpack Rev. A

### ISSUE THREAD

**Issue by sabas1080** [nodemcu/nodemcu-devkit-v1.0#13]
A group of friends and I made a backpack for 1.0v NodeMcu hope you like it, we welcome your comments

https://www.tindie.com/products/sabas1080/nodemcu-v10-esp8266-lipolyliion-backpack-rev-a/

Discount code: BBF6B2F

Thanks

**Comment by asetyde** [comment]
Please correct Link with spots

> https://www.tindie.com/products/sabas1080/nodemcu-v10-esp8266-lipolyliion-backpack-rev-a/
> 
it's very interesting but also indicate a battery to combine .. and capacity duration etc
