### ISSUE TITLE
Eagle library for Nodemcu Lolin V3

### ISSUE THREAD

**Issue by irwanayeah** [nodemcu/nodemcu-devkit-v1.0#19]
Hello gentleman,
I would like to use Nodemcu Lolin V3 as a part in my PCB layout. But I can't find any library for Eagle. Is there any existing one? Or does anybody plan to create one?
Thanks.

**Comment by sturze** [comment]
me too! still nothing... nowhere...

**Comment by vowstar** [comment]
@irwanayeah @sturze Hello, Lolin V3 is not official board, the official latest board is nodemcu-devkit-v1.0
And, we don't authorization Lolin V3 use the name Nodemcu.

**Comment by Eltronas** [comment]
https://mega.nz/#!1t8jzSqb!doaTLDcj8MVNFQ1ReJRFOIpOO0-HCy4FIjuXTIL_IVw

I create one, I hope I've helped :)

**Comment by cmedinam** [comment]
Eltronas I thing your package is wrong, Its weight is wrong or there are diferent sizes of the "same" board.

**Comment by shasan247** [comment]
Eltronas, do you have any library for V2???

**Comment by patavium73** [comment]
guardate questo che funziona https://www.arduinotronics.com/nodemcu-lolin-v-3-eagle-library/

**Comment by HADIUU07** [comment]
> guardate questo che funziona https://www.arduinotronics.com/nodemcu-lolin-v-3-eagle-library/

can you sent link again ? the link expired
