### ISSUE TITLE
MAC AIR and USB PORT not showing up with NODEMCU CP2102 (1.0)

### ISSUE THREAD

**Issue by XicoBHZ** [nodemcu/nodemcu-devkit-v1.0#24]
Guys, can you help me. I've just got my NODEMCU ESP-12e with CP2102 (1.0), I'm using a MAC AIR, but the device doesn't appear on the PORT list, as some of the guys above. I'be tried different cables as well a USB interface that allows me to input an extra 5V DC PSU to feed the NODEMCU, no response at all. The Blink sketch compiles OK, the board is correctly set for NODEMCU 1.0 (ESP-12e Module), but no way to make it works. I heard that I should download a driver for CP2102, is it right? If so, where can I find it? Any help? Thanks!

**Comment by vowstar** [comment]
You can use homebrew install it.

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null
and press enter/return key. Wait for the command to finish.
Run:
brew cask install silicon-labs-vcp-driver

http://macappstore.org/silicon-labs-vcp-driver/
