### ISSUE TITLE
Pinout Documentation

### ISSUE THREAD

**Issue by mrleongalaxyum** [nodemcu/nodemcu-devkit-v1.0#44]
Hello,
Since I'm not able to send you an email, I'll try contacting you this way. 
I'm interested in software/template you used to generate the following pinout image:

![image](https://user-images.githubusercontent.com/51249624/99161440-a2311980-26f2-11eb-90d4-7e298a8c59d0.png)

I'm currently working on a LoRaWAN node device which will have quite a bit of headers so I'm interested in creating a similar pinout graphic.

Best regards,
Leon

**Comment by vowstar** [comment]
[NODEMCU-DEVKIT-V1.0-INSTRUCTION-EN.zip](https://github.com/nodemcu/nodemcu-devkit-v1.0/files/5541772/NODEMCU-DEVKIT-V1.0-INSTRUCTION-EN.zip)

This was a very old story. In the past years I use M$ word. Now I'm using draw.io

**Comment by mrleongalaxyum** [comment]
Thanks a lot!
