### ISSUE TITLE
altium Vowstar_* library

### ISSUE THREAD

**Issue by bakroistvan** [nodemcu/nodemcu-devkit-v1.0#6]
Is it possible to publish the Vowstar_*.IntLib files?

**Comment by vowstar** [comment]
Yes, but you can use altum's "make PCB library" to get this easily.

**Comment by bakroistvan** [comment]
by the way, Did you use some program to make this picture?

![PIN MAP](https://raw.githubusercontent.com/nodemcu/nodemcu-devkit-v1.0/master/Documents/NODEMCU_DEVKIT_V1.0_PINMAP.png)

**Comment by vowstar** [comment]
@bakroistvan This picture is made by Microsoft Word 2013
