### ISSUE TITLE
Files for V2.0

### ISSUE THREAD

**Issue by chrisfraser** [nodemcu/nodemcu-devkit-v1.0#8]
Hi there guys.

Awesome work on this project. I have a V2 board and cannot find the files anywhere. Do you plan on putting them up?

**Comment by Orgmar** [comment]
NodeMCU only released V0.9 and V1.0 board. The next is V1.1, we plan to release it in 2016. May be you got a fake one.

**Comment by vowstar** [comment]
NodeMCU have no V3,V2 board. Next is V1.1, and comes 2016.

**Comment by vowstar** [comment]
Maybe you got a fake one, at the back of the board you will see v1.0 version, and latest official board(v1.0) uses CP2102 and LM1117(not AMS1117)
